name: CD Development

on:
  push:
    paths:
      - 'firebase/**'
    branches:
      - main

jobs:
  # どのサービスをデプロイするかを確認する
  changes:
    name: Changes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      functions: ${{ steps.filter.outputs.functions }}
      hosting: ${{ steps.filter.outputs.hosting }}
    steps:
      # ソースコードをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v2

      # 変更を検出する
      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            functions:
              - 'functions/**'
            hosting:
              - 'hosting/**'

  deploy_functions:
    name: Deploy Functions
    needs:
      - changes
    if: ${{ needs.changes.outputs.functions == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 60
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_FIREBAE }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_MAIL_FIREBASE }}
          create_credentials_file: true
          export_environment_variables: true
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
        working-directory: ./functions
      - name: Deploy to Functions
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions --force --project=${{ secrets.PROJECT_ID }}

  deploy_hosting:
    name: Deploy Hosting
    needs:
      - changes
    if: ${{ needs.changes.outputs.hosting == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 60
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_FIREBAE }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_MAIL_FIREBASE }}
          create_credentials_file: true
          export_environment_variables: true
      - name: Deploy to Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --force --project=${{ secrets.PROJECT_ID }}