name: Firebase CI

on:
  pull_request:
    paths:
      - 'firebase/**'
    types:
      - opened
      - synchronize

jobs:
  # Functions への変更をチェックする
  changes:
    name: Changes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      functions: ${{ steps.filter.outputs.functions }}
    steps:
      # ソースコードをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v2

      # 変更を検出する
      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            functions:
              - 'functions/**'

  # Firebase Functions の CI
  deploy_functions:
    name: Deploy Functions
    needs:
      - changes
    if: ${{ needs.changes.outputs.functions == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 15
    steps:
      # ソースコードをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v2

      # node のセットアップ
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
        working-directory: ./functions

      # リントエラーのチェック
      - name: Check for linting errors
        run: npm run lint
        working-directory: ./functions